name: Build
on:
  push:
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          submodules: 'recursive'
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dsp.so
          path: build/dsp.so
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          submodules: 'recursive'
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dsp.dll
          path: build/dsp.dll
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          submodules: 'recursive'
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dsp.dylib
          path: build/dsp.dylib
